In [2]:
import numpy as np
array

In [64]:
a=np.array([[1,2,-1],
            [1,1,-3]])
b=np.array([[3,2,-2],
            [-1,2,1]])
c=np.array([[3],[1],[2]])
d=np.array([[3,2],
            [1,1],
            [2,-1]])

In [60]:
a

array([[ 1,  2, -1],
       [ 1,  1, -3]])

In [49]:
b

array([[ 3,  2, -2],
       [-1,  2,  1]])

In [66]:
c

array([[3],
       [1],
       [2]])

In [55]:
d

array([[ 3,  2],
       [ 1,  1],
       [ 2, -1]])

In [50]:
#질문 1번
print(a+b)

[[ 4  4 -3]
 [ 0  3 -2]]


In [62]:
#질문 2번
arraydot=np.dot(a,c)
arraydot[0,0]

3

In [63]:
#질문 3번
arraydot=np.dot(a,d)
arraydot[0,1]

5