In [1]:
import numpy#numpy 불러오기

In [2]:
array1=numpy.array([2,3,5,7,11,13,17,19])#numpy array 함수 사용

In [3]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19])

In [4]:
type(array1)
#array1의 type이 궁금하다~ nadarray는 n차원배열을 의미함

numpy.ndarray

In [5]:
array1.shape#array1에 몇 개의 요소가 있는지 확인하기(shape)

(8,)

In [7]:
array2=numpy.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [8]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
array2.shape #3x4

(3, 4)

In [12]:
array1.size

8

In [13]:
array2.size #3x4

12

In [27]:
import numpy

array1=numpy.full(6, 0)
array2=numpy.random.random(6)

In [30]:
array1

array([0, 0, 0, 0, 0, 0])

In [31]:
array2

array([0.90827524, 0.3693943 , 0.16293609, 0.13139096, 0.19189378,
       0.22768384])

In [21]:
import numpy as np

array1=np.full(6,0)
array2=np.random.random(6)

In [22]:
array1

array([0, 0, 0, 0, 0, 0])