In [ ]:
#실습과제

In [38]:
import numpy as np
array

array([[ 0,  2],
       [ 1, -1],
       [ 3, -4]])

In [28]:
a=np.array([[1,2,3]
            ,[-1,0,2]
            ,[3,4,5]
            ,[2,-2,-3]])

In [32]:
a

array([[ 1,  2,  3],
       [-1,  0,  2],
       [ 3,  4,  5],
       [ 2, -2, -3]])

In [56]:
a[1][1] #=>a[1,1]

0

In [57]:
a[1,1]

0

In [35]:
array
b=np.array([[0,2],[1,-1],[3,-4]])

In [36]:
b

array([[ 0,  2],
       [ 1, -1],
       [ 3, -4]])

In [37]:
b[2][0] #=>b[2,0]

3