In [1]:
#평균값 mean

In [2]:
import numpy as np

In [3]:
array1=np.array([14,6,13,21,23,31,9,5])

In [4]:
print(array1.mean())

15.25


In [5]:
#중앙값 median(중앙에 있는 값)

In [14]:
import numpy as np
array1=np.array([8,12,9,15,16])
array2=np.array([14,6,13,21,23,31,9,5])

In [16]:
print(np.median(array1))
print(np.median(array2))

12.0
13.5


In [19]:
#2중 리스트
import numpy as np
b=np.array([[0,1,2],[3,4,5]])
print(b)

[[0 1 2]
 [3 4 5]]


In [20]:
#3중 배열 리스트
import numpy as np
c=np.array([[[0,1,2],[3,4,5]],[[5,4,3],[2,1,3]]])
print(c)

[[[0 1 2]
  [3 4 5]]

 [[5 4 3]
  [2 1 3]]]


In [24]:
import numpy as no
d=np.zeros(8) #0이 8개 저장된 배열
#숫자 단어만 수정하면 원하는 숫자로 가능함
print(d)
e=np.ones(8) #1이 8개 저장된 배열
print(e)
f=np.arange(8) #0부터 7까지가 저장된 배열
print(f)

[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7]


In [25]:
#shape()함수에 의해 배열의 형태를 얻는다
import numpy as np
a=np.array([[0,1,2],
              [3,4,5]]) #2x3의 2차원배열
print(np.shape(a))

(2, 3)


In [26]:
print(len(a)) #a의 행 수를 얻는다

2


배열과 수치의 연산

In [28]:
import numpy as np
a=np.array([[0,1,2],
              [3,4,5]])
print(a)
print()
print(a+3)
print()
print(a*3)

[[0 1 2]
 [3 4 5]]

[[3 4 5]
 [6 7 8]]

[[ 0  3  6]
 [ 9 12 15]]


In [29]:
#배열끼리의 연산
b=np.array([[0,1,2],
               [3,4,5]]) #2차원 배열
c=np.array([[2,0,1],
               [5,3,4]])
print(b)
print()
print(c)
print()
print(b+c)
print()
print(b*c) #위의 행은 위의 행끼리, 아래행은 아래행끼리만 곱해짐
#b와 c 행렬 곱셈을 성립할 수 없음

[[0 1 2]
 [3 4 5]]

[[2 0 1]
 [5 3 4]]

[[2 1 3]
 [8 7 9]]

[[ 0  0  2]
 [15 12 20]]


In [31]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a[3])#인덱스를 지정

4


In [32]:
#배열 수정하기
a[2]=9
print(a)

[1 2 9 4 5]


In [33]:
#[1,2]행 찾기
b=np.array([[0,1,2],
            [3,4,5]])
print(b[1,2])#b[1][2]와 같다

5


In [34]:
b[1,2]=9#b [1행 2열]을 9로 바꾸고 싶을 때
print(b)

[[0 1 2]
 [3 4 9]]


In [35]:
c=np.array([[0,1,2],
               [3,4,5]])
print(c[1, :]) #인덱스가 1인 행을 취득
print()
c[:,1]=np.array([6,7])#인덱스가 1인 열을 교체
print(c)

[3 4 5]

[[0 6 2]
 [3 7 5]]


In [37]:
#각 원소들 사이의 계산
import numpy as np
a=np.array([[0,1,2],
               [3,4,5]])#2차원 배열
print('합계:', np.sum(a))
print('평균:', np.average(a))
print('최댓값:', np.max(a))
print('최솟값:', np.min(a))

합계: 15
평균: 2.5
최댓값: 5
최솟값: 0


In [40]:
#문제
'''
a,b의 곱셈과 더하기를 구해보아라.
'''

import numpy as np
a=np.array([[0,1,2],
               [3,4,5]])
b=np.array([[5,4,3],
               [2,1,0]])
print(a*b)
print()
print(a+b)
print()
print(a-b)

[[0 4 6]
 [6 4 0]]

[[5 5 5]
 [5 5 5]]

[[-5 -3 -1]
 [ 1  3  5]]


In [47]:
#행렬 곱하기 *dot을 썼을 떄 행렬 곱셈이 가능한지 꼭 알아보기
#a랑 d 곱하기 => dot(a,d)
import numpy as np
a=np.array([[0,1,2],
            [1,2,3]])
b=np.array([[2,1],
            [2,1],
            [2,1]])
print(np.dot(a,b))

c=np.array([[0,1,2],
             [3,4,5],
             [6,7,8]])
d=np.array([[0,2,0],
           [2,0,2],
           [0,2,0]])
print()
#행렬별 곱
print(np.dot(c,d))

[[ 6  3]
 [12  6]]

[[ 2  4  2]
 [ 8 16  8]
 [14 28 14]]
